// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flluter2cpi/pages/Post%20&%20Comment%20classes/comment_class.dart';
import 'package:flluter2cpi/pages/Post%20&%20Comment%20classes/distinct_tags.dart';
import 'package:flluter2cpi/pages/Post-Info/Post_info_v.dart';

import '../../test.dart';
import '../Post/post_v.dart';

List<Post> ePosts = [
  for(var i in originalETags)
  Post(
    type: "StuckPosts",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: DateTime.now(),
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: i,
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  for(var i in originalETags)
  Post(
    type: "StuckPosts",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: DateTime.now(),
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: i,
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
];
List<Post> aPosts = [
   
  Post(
    type: "academicPosts",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: DateTime.now(),
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "Algebra 1",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  Post(
    type: "academicPosts",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: DateTime.now(),
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "Algebra 2",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
];
List<Post> infoPosts = [
   Post(
    type: "academicPosts",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: DateTime.now(),
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "Campus",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  Post(
    type: "academicPosts",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: DateTime.now(),
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "General",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  Post(
    type: "academicPosts",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: DateTime.now(),
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "General",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  Post(
    type: "academicPosts",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: DateTime.now(),
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "General",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  Post(
    type: "academicPosts",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: DateTime.now(),
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "General",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: DateTime.now(),
          profilePic: null,
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
];
// can be from stack or academic or info "that can be liked"
List<PostInfo> articlePosts = [
  PostInfo(image: image, title: "sdfsdfsdfs", description: "sdfsdkjfsjhfsdfksd", date: DateTime.now(),),
  PostInfo(image: image, title: "sdfsdfsdfs", description: "sdfsdkjfsjhfsdfksd", date: DateTime.now(),),
  PostInfo(image: image, title: "sdfsdfsdfs", description: "sdfsdkjfsjhfsdfksd", date: DateTime.now(),),
  PostInfo(image: image, title: "sdfsdfsdfs", description: "sdfsdkjfsjhfsdfksd", date: DateTime.now(),),
  PostInfo(image: image, title: "sdfsdfsdfs", description: "sdfsdkjfsjhfsdfksd", date: DateTime.now(),),
];
List<String> followedTags = [];
List<String> originalETags = [
  "Pascal",
  "Python",
  "Java",
  "C#",
  "C",
  "C++",
  "Django",
  "TypeScript",
  "React native",
  "Jquery",
  "CSS",
  "SQL",
  "MySql",
  "Node js",
  "React js",
  "Php",
  "JavaScript",
  "Android Studio",
  "Linux",
  "Ruby",
  "XML",
  "Firebase",
  "HTML",
  "Nest js",
  ".net",
];
List<String> eTags = [
  "Pascal",
  "Python",
  "Java",
  "C#",
  "C",
  "C++",
  "Django",
  "TypeScript",
  "React native",
  "Jquery",
  "CSS",
  "SQL",
  "MySql",
  "Node js",
  "React js",
  "Php",
  "JavaScript",
  "Android Studio",
  "Linux",
  "Ruby",
  "XML",
  "Firebase",
  "HTML",
  "Nest js",
  ".net",
];
