// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flluter2cpi/pages/Post%20&%20Comment%20classes/comment_class.dart';
import 'package:flluter2cpi/pages/Post%20&%20Comment%20classes/distinct_tags.dart';

import '../../test.dart';

import '../Post-Info/post_info_v.dart';
import '../Post/post_v.dart';

List<Post> ePosts = [
  for(var i in originalETags)
  Post(
    image: "",
    type: "StuckPosts",
    profilePic: "",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: "2023-05-17",
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: i,
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          commentId: "",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentId: "",
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  for(var i in originalETags)
  Post(
    image: "",
    type: "StuckPosts",
    likesCount: 3,
    profilePic: "",
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: "2023-05-17",
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: i,
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentId: "",
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          commentId: "",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
];
List<Post> aPosts = [
   
  Post(
    image: "",
    type: "academicPosts",
    profilePic: "",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: "2023-05-17",
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "Algebra 1",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentId: "",
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          commentId: "",
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  Post(
    image: "",
    type: "academicPosts",
    likesCount: 3,
    profilePic: "",
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: "2023-05-17",
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "Algebra 2",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          commentId: "",
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          commentId: "",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  Post(
    image: "",
    type: "academicPosts",
    profilePic: "",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: "2023-05-17",
    
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "Algebra 2",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          commentId: "",
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          commentId: "",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),Post(
    type: "academicPosts",
    profilePic: "",
    image: "",
    likesCount: 3,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: "2023-05-17",
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "Algebra 2",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          commentId: "",
          likesCount: 14,
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          commentId: "",
          likesCount: 10,
          commentsCount: 0,
          date: "2023-06-02 12:12",
          profilePic: "",
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
];
List<Post> infoPosts = [
   Post(
    type: "academicPosts",
    image: "",
    likesCount: 3,
    profilePic: "",
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: "2023-05-17",
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "Campus",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          commentId: "",
          likesCount: 14,
          commentsCount: 0,
          date: "",
          profilePic:"",
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          commentId: "",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: "DateTime.now()",
          profilePic: "",
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  Post(
    type: "academicPosts",
    image: "",
    likesCount: 3,
    profilePic:"" ,
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: "2023-05-17",
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "General",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          commentId: "",
          likesCount: 14,
          commentsCount: 0,
          date: "DateTime.now()",
          profilePic: "",
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          commentId: "",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  Post(
    type: "academicPosts",
    likesCount: 3,
    image: "",
    profilePic: "",
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: "2023-05-17",
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "General",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          commentId: "",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          commentId: "",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: "2023-05-17 17:17",
          profilePic: "",
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  Post(
    type: "academicPosts",
    likesCount: 3,
    image: "",
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: "2023-05-17",
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    
    tag: "General",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          commentId: "",
          isLiked: true),
      CommentClass(
          userName: "Younes",
          commentId: "",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    profilePic: "",
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
  Post(
    type: "academicPosts",
    likesCount: 3,
    profilePic: "",
    image: "",
    commentsCount: 2,
    title: "this is a title ",
    description: "kjhfkjewhfwkfe",
    date: "2023-05-17",
    userName: "Aboubakr",
    email: "la.belmiloud@esi-sba.dz",
    tag: "General",
    comments: [
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 14,
          commentsCount: 0,
          date: "",
          profilePic: "",
          commentId: "",
          links: ["", "", ""],
          isLiked: true),
      CommentClass(
          userName: "Younes",
          email: "y.ferhat@esi-sba.dz",
          comment: "this is the comment of younes",
          likesCount: 10,
          commentsCount: 0,
          date: "",
          commentId: "",
          profilePic: "",
          links: ["", "", ""],
          isLiked: false),
    ],
    isLiked: true,
    controllerTag: generateTag(),
    links: ["", "", ""],
  ),
];
// can be from stack or academic or info "that can be liked"
List<PostInfo> articlePosts = [
 /*PostInfo(image: null!, title: "sdfsdfsdfs", description: "sdfsdkjfsjhfsdfksd", date: "2023-05-11 11:11",),
  PostInfo(image: null!, title: "sdfsdfsdfs", description: "sdfsdkjfsjhfsdfksd", date: "2023-05-11 11:11",),
  PostInfo(image: null!, title: "sdfsdfsdfs", description: "sdfsdkjfsjhfsdfksd", date: "2023-05-11 11:11",),
  PostInfo(image: null!, title: "sdfsdfsdfs", description: "sdfsdkjfsjhfsdfksd", date: "2023-05-11 11:11",),
  PostInfo(image: null!, title: "sdfsdfsdfs", description: "sdfsdkjfsjhfsdfksd", date: "2023-05-11 11:11",),*/
];
List<String> followedTags = [];
List<String> originalETags = [
  "Pascal",
  "Python",
  "Java",
  "C#",
  "C",
  "C++",
  "Django",
  "TypeScript",
  "React native",
  "Jquery",
  "CSS",
  "SQL",
  "MySql",
  "Node js",
  "React js",
  "Php",
  "JavaScript",
  "Android Studio",
  "Linux",
  "Ruby",
  "XML",
  "Firebase",
  "HTML",
  "Nest js",
  ".net",
];
List<String> eTags = [
  "Pascal",
  "Python",
  "Java",
  "C#",
  "C",
  "C++",
  "Django",
  "TypeScript",
  "React native",
  "Jquery",
  "CSS",
  "SQL",
  "MySql",
  "Node js",
  "React js",
  "Php",
  "JavaScript",
  "Android Studio",
  "Linux",
  "Ruby",
  "XML",
  "Firebase",
  "HTML",
  "Nest js",
  ".net",
];
